export type Participant = {
  id: number;
  nomeCompleto: string;
  dtNascimento: string | Date;
  rg: string;
  cpf: string;
  telefone: string;
  celular: string;
  telefoneResponsavel: string;
  celularResponsavel: string;
  email: string;
  genero: string;
  federado: boolean;
  clube: string;
  modalidade: string;
  dataInicioFederado: string | Date;
  logradouro: string;
  numeroEndereco: string;
  cep: string;
  estado: string;
  cidade: string;
  complemento: string;
  tipoSanguineo: string;
  alergias: string;
  enfermidade: string;
  restricaoAlimentar: string;
  alergiaMedicamentosa: string;
};
